apps/guestbook/urls.py
from django.urls import path

from . import views


app_name = 'guestbook'

urlpatterns = [
    path('', views.GuestbookView.as_view(), name='index'),
    path('add/', views.GuestbookCreateView.as_view(), name='add'),
    path('<int:pk>/delete/', views.GuestbookDeleteView.as_view(), name='delete')
]

openshift_guestbook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('apps.guestbook.urls', namespace='guestbook')),
]

apps/guestbook/models.py
from django.db import models


class Guestbook(models.Model):
    message = models.CharField(
        'Message',
        max_length=250,
    )

apps/guestbook/forms.py
from django import forms

from .models import Guestbook


class GuestbookForm(forms.ModelForm):
    class Meta:
        model = Guestbook
        fields = '__all__'

apps/guestbook/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView

from .forms import GuestbookForm
from .models import Guestbook


class GuestbookView(ListView):
    model = Guestbook
    context_object_name = 'guestbook_entries'

class GuestbookCreateView(CreateView):
    model = Guestbook
    form_class = GuestbookForm
    context_object_name = 'guestbook_entry'
    success_url = reverse_lazy('guestbook:index')

class GuestbookDeleteView(DeleteView):
    model = Guestbook
    context_object_name = 'guestbook_entry'
    success_url = reverse_lazy('guestbook:index')

apps/guestbook/templates/guestbook/guestbook_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="card shadow-sm">
        <div class="card-header text-center">
            <h4 class="my-0 font-weight-normal">Delete Entries</h4>
        </div>
        <div class="card-body text-left">
            <form method="post">
                {% csrf_token %}

                <p>
                    Are you sure you want to delete this entry?
                </p>

                <p>
                    <code>{{ guestbook_entry.message }}</code>
                </p>

                <p class="text-center">
                    <a href="{% url 'guestbook:index' %}" class="btn btn-lg btn-outline-secondary">
                        Cancel
                    </a>
                    <button type="submit" class="btn btn-lg btn-primary">
                        <i class="fas fa-trash"></i> Delete
                    </button>
                </p>
            </form>
        </div>
    </div>
</div>
{% endblock %}

apps/guestbook/templates/guestbook/guestbook_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="card shadow-sm">
        <div class="card-header text-center">
            <h4 class="my-0 font-weight-normal">New Entry</h4>
        </div>
        <div class="card-body text-left">
            <form method="post">
                {% include 'guestbook/snippets/form.html' %}

                <p class="text-center">
                    <a href="{% url 'guestbook:index' %}" class="btn btn-lg btn-outline-secondary">
                        Cancel
                    </a>
                    <button type="submit" class="btn btn-lg btn-primary">
                        <i class="fas fa-save"></i> Save
                    </button>
                </p>
            </form>
        </div>
    </div>
</div>
{% endblock %}

apps/guestbook/templates/guestbook/guestbook_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="card shadow-sm">
        <div class="card-header text-center">
            <h4 class="my-0 font-weight-normal">Guestbook Entries</h4>
        </div>
        <ul class="list-group list-group-flush">
            {% for guestbook_entry in guestbook_entries %}
                <li class="list-group-item">
                    {{ guestbook_entry.message }}

                    <span class="float-right">
                        <a href="{% url 'guestbook:delete' guestbook_entry.pk %}" class="mx-2 text-danger">
                            <i class="fas fa-trash" title="Delete"></i>
                        </a>
                    </span>
                </li>
            {% empty %}
                <li class="list-group-item">There are not any guestbook entries.</li>
            {% endfor %}
        </ul>
        <div class="card-body text-center">
            <a href="{% url 'guestbook:add' %}" class="btn btn-lg btn-outline-primary">
                <i class="fas fa-plus"></i> New Entry
            </a>
        </div>
    </div>
</div>
{% endblock %}

apps/guestbook/templates/guestbook/snippets/form.html
{% load widget_tweaks %}

{% csrf_token %}

{% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        <p><strong>The following errors occurred:</strong></p>

        {{ form.non_field_errors }}
    </div>
{% endif %}

{% for field in form %}
    <div class="form-group">
        <strong>
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        </strong>

        {{ field | add_class:'form-control' }}

        {% if field.help_text %}
            <small class="form-text text-muted">
                {% autoescape off %}
                    {{ field.help_text }}
                {% endautoescape %}
            </small>
        {% endif %}

        {% if field.errors %}
            {% for error in field.errors %}
                <p class="text-danger">{{ error }}</p>
            {% endfor %}
        {% endif %}
    </div>
{% endfor %}

<hr class="my-4" />

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>OpenShift Guestbook</title>

    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
        crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
</head>

<body>
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">OpenShift Guestbook</h1>
        <p class="lead">
            Welcome to your OpenShift Guestbook! This is an example application built to run on OpenShift.
        </p>
    </div>

    {% block content %}
        <p>No content available for this page.</p>
    {% endblock %}

    <div class="container">
        <footer class="pt-4 my-md-5 pt-md-5 border-top text-center">
            <div>
                <strong>Server Hostname:</strong>
                <br />
                <code>{{ request.META.SERVER_NAME }}</code>
            </div>

            <div class="logo">
                <a href="https://www.openshift.com/"></a>
            </div>
        </footer>
    </div>

    <!-- global scripts -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/all.js" integrity="sha384-xymdQtn1n3lH2wcu0qhcdaOpQwyoarkgLVxC/wZ5q7h9gHtxICrpcaSUfygqZGOe" crossorigin="anonymous"></script>
</body>

</html>